services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/src:/app/src
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src
    restart: unless-stopped